git submodule add https://github.com/Valloric/YouCompleteMe.git	bundle/YouCompleteMe
git submodule add https://github.com/rking/ag.vim.git	bundle/ag.vim
git submodule add https://github.com/rosenfeld/conque-term.git	bundle/conque-term
git submodule add https://github.com/ctrlpvim/ctrlp.vim.git	bundle/ctrlp.vim
git submodule add https://github.com/haya14busa/incsearch-easymotion.vim.git	bundle/incsearch-easymotion.vim
git submodule add https://github.com/haya14busa/incsearch.vim.git	bundle/incsearch.vim
git submodule add https://github.com/fholgado/minibufexpl.vim.git	bundle/minibufexpl.vim
git submodule add https://github.com/Shougo/neocomplete.vim.git	bundle/neocomplete.vim
git submodule add git://github.com/scrooloose/nerdtree.git	bundle/nerdtree
git submodule add https://github.com/majutsushi/tagbar.git	bundle/tagbar
git submodule add https://github.com/easymotion/vim-easymotion.git	bundle/vim-easymotion
git submodule add https://github.com/tpope/vim-fugitive	bundle/vim-fugitive
git submodule add https://github.com/fatih/vim-go.git	bundle/vim-go
git submodule add https://github.com/nathanaelkane/vim-indent-guides	bundle/vim-indent-guides
git submodule add https://github.com/Lokaltog/vim-powerline.git	bundle/vim-powerline
git submodule add https://github.com/derekwyatt/vim-scala.git	bundle/vim-scala
git submodule add https://github.com/tpope/vim-surround.git	bundle/vim-surround
git submodule add https://github.com/Shougo/vimproc.vim.git	bundle/vimproc.vim
git submodule add git@github.com:Shougo/vimshell.vim.git	bundle/vimshell.vim
