cd YouCompleteMe/ && git remote -v
cd ../ag.vim/ && git remote -v
cd ../conque-term/ && git remote -v
cd ../ctrlp.vim/ && git remote -v
cd ../incsearch-easymotion.vim/ && git remote -v
cd ../incsearch.vim/ && git remote -v
cd ../minibufexpl.vim/ && git remote -v
cd ../neocomplete.vim/ && git remote -v
cd ../nerdtree/ && git remote -v
cd ../tagbar/ && git remote -v
cd ../vim-easymotion/ && git remote -v
cd ../vim-fugitive/ && git remote -v
cd ../vim-go/ && git remote -v
cd ../vim-indent-guides/ && git remote -v
cd ../vim-latex/ && git remote -v
cd ../vim-powerline/ && git remote -v
cd ../vim-scala/ && git remote -v
cd ../vim-surround/ && git remote -v
cd ../vimproc.vim/ && git remote -v
cd ../vimshell.vim/ && git remote -v
cd ../vjde/ && git remote -v
